from __future__ import annotations

MESSAGES = {
    "ru": {
        "welcome": "Привет! Я бот-Гадалка. Помогу сделать расклад по таро.",
        "help": "Доступные команды:\n/menu — главное меню\n/profile — показать профиль\n/language — сменить язык\nИспользуйте кнопки ниже.",
        "ask_language": "Выберите язык (ru/en). По умолчанию — ru.",
        "ask_name": "Введите имя/ник (можно оставить текущее)",
        "ask_birthdate": "Введите дату рождения (ДД.ММ.ГГГГ или YYYY-MM-DD)",
        "ask_gender": "Укажите пол (м/ж) или пропустите",        
        "saved": "Сохранено.",
        "unknown_language": "Пожалуйста, отправьте ru или en.",
        "profile": "Профиль:\nИмя: {name}\nДата рождения: {birthdate}\nПол: {gender}\nЯзык: {language}",
        "menu": "Главное меню",
        "limit_reached": "Достигнут дневной лимит бесплатных раскладов. Попробуйте завтра или оформите премиум.",
        "tarot_prompt": "Выберите тип расклада",
        "numerology_prompt": "Выберите расчёт",
        "astro_prompt": "Введите дату рождения в формате ДД.ММ.ГГГГ",
        "bad_date": "Не смог распознать дату. Попробуйте ещё раз.",
        "compat_second": "Введите дату рождения второго человека",
        "compat_first": "Введите дату рождения первого человека (ДД.ММ.ГГГГ)",
        "name_prompt": "Введите имя или ник для расчёта",
        "broadcast_ack": "Рассылка отправлена {count} пользователям.",
        "broadcast_usage": "Используйте: /broadcast <текст>",
        "delay_usage": "Используйте: /set_delay <секунды>. 0 — без задержки.",
        "delay_invalid": "Укажите неотрицательное целое число секунд.",
        "delay_updated": "Задержка ответов установлена: {seconds} с.",
        "admin_denied": "Доступ запрещён",
        "delete_confirm": "Удалить все сохранённые данные? Ответьте 'да' или 'нет'.",
        "delete_done": "Данные удалены.",
        "delete_cancel": "Удаление отменено.",
        "delete_prompt": "Пожалуйста, ответьте 'да' или 'нет'.",
        "limit_info": "Осталось бесплатных раскладов сегодня: {remaining}",
        "random_result": "Случайный расклад ({system}):\n{result}",
        "feature_unavailable": "Сейчас работаем над Таро. Другие направления временно недоступны.",
        "metaphor": "Метафора дня: {text}",
        "rune": "Руна дня: {name} — {meaning}",
        "admin_panel": "Админ-панель. Выберите действие:",
        "admin_broadcast_prompt": "Отправьте текст рассылки или напишите 'отмена'.",
        "admin_broadcast_cancel": "Рассылка отменена.",
        "referral_welcome_with_bonus": "Добро пожаловать! Ты пришёл по приглашению {inviter}. Тебе начислено {bonus} приветственных раскладов 🎁",
        "referral_welcome_no_bonus": "Добро пожаловать! Ты пришёл по приглашению {inviter}. Бесплатные расклады можно получить в меню.",
        "referral_notif_inviter": "Твой друг {invited} присоединился. Начислено +{bonus}. Баланс: {balance}.",
        "invite_link": "Вот твоя ссылка ✨\\n{link}\\n\\nЗа каждого друга: +{bonus} бесплатных раскладов.\\nПриветственный бонус другу: +{welcome_bonus}.",
        "invite_disabled": "Реферальная система временно отключена.",
        "referral_stats_user": "Вы пригласили: {count}\nБонусов осталось: {balance}",
        "referral_bonus_updated": "Бонус за приглашение: {bonus}",
        "referral_welcome_bonus_updated": "Приветственный бонус: {bonus}",
        "referral_bonus_usage": "Используйте: /set_ref_bonus <число>",
        "referral_welcome_usage": "Используйте: /set_ref_welcome <число>",
        "referral_system_enabled": "Реферальная система включена.",
        "referral_system_disabled": "Реферальная система выключена.",
        "referral_admin_stats": "Всего приглашённых: {total}\nТекущий бонус: {bonus}\nТоп-10:\n{leaders}",
        "referral_settings_panel": "Настройки рефералов:\nБонус за друга: {bonus}\nПриветственный бонус: {welcome_bonus}\nСтатус: {status}",
    },
    "en": {
        "welcome": "Hi! I'm the Fortune Teller bot. I can draw tarot spreads for you.",
        "help": "Available commands:\n/menu — main menu\n/profile — profile\n/language — choose language\nUse the buttons below.",
        "ask_language": "Choose language (ru/en). Default is ru.",
        "ask_name": "Send your name/nickname (or keep current)",
        "ask_birthdate": "Send your birth date (DD.MM.YYYY or YYYY-MM-DD)",
        "ask_gender": "Provide gender (m/f) or skip",
        "saved": "Saved.",
        "unknown_language": "Please send ru or en.",
        "profile": "Profile:\nName: {name}\nBirth date: {birthdate}\nGender: {gender}\nLanguage: {language}",
        "menu": "Main menu",
        "limit_reached": "Daily free limit reached. Try tomorrow or upgrade to premium.",
        "tarot_prompt": "Choose a tarot spread",
        "numerology_prompt": "Choose a calculation",
        "astro_prompt": "Send your birth date (DD.MM.YYYY)",
        "bad_date": "Could not parse the date. Try again.",
        "compat_second": "Enter birth date of the second person",
        "compat_first": "Enter birth date of the first person (DD.MM.YYYY)",
        "name_prompt": "Enter a name or nickname to calculate",
        "broadcast_ack": "Broadcast sent to {count} users.",
        "broadcast_usage": "Usage: /broadcast <text>",
        "delay_usage": "Usage: /set_delay <seconds>. 0 = no delay.",
        "delay_invalid": "Provide a non-negative whole number of seconds.",
        "delay_updated": "Response delay set to {seconds} s.",
        "admin_denied": "Access denied",
        "delete_confirm": "Delete all saved data? Answer 'yes' or 'no'.",
        "delete_done": "Data deleted.",
        "delete_cancel": "Deletion cancelled.",
        "delete_prompt": "Please answer 'yes' or 'no'.",
        "limit_info": "Free draws left today: {remaining}",
        "random_result": "Random spread ({system}):\n{result}",
        "feature_unavailable": "We're focusing on Tarot right now. Other features are temporarily unavailable.",
        "metaphor": "Metaphor of the day: {text}",
        "rune": "Rune of the day: {name} — {meaning}",
        "admin_panel": "Admin panel. Choose an action:",
        "admin_broadcast_prompt": "Send broadcast text or type 'cancel'.",
        "admin_broadcast_cancel": "Broadcast cancelled.",
        "referral_welcome_with_bonus": "Welcome! You joined via {inviter}. You've received {bonus} welcome draws 🎁",
        "referral_welcome_no_bonus": "Welcome! You joined via {inviter}. You can get free draws in the menu.",
        "referral_notif_inviter": "Your friend {invited} started using the bot. +{bonus} bonus added. Balance: {balance}.",
        "invite_link": "Your magic link ✨\\n{link}\\n\\nPer friend: +{bonus} free draws.\\nFriend welcome bonus: +{welcome_bonus}.",
        "invite_disabled": "Referral system is temporarily disabled.",
        "referral_stats_user": "Invited friends: {count}\nBonus balance: {balance}",
        "referral_bonus_updated": "Referral bonus set to {bonus}.",
        "referral_welcome_bonus_updated": "Welcome bonus set to {bonus}.",
        "referral_bonus_usage": "Usage: /set_ref_bonus <number>",
        "referral_welcome_usage": "Usage: /set_ref_welcome <number>",
        "referral_system_enabled": "Referral system enabled.",
        "referral_system_disabled": "Referral system disabled.",
        "referral_admin_stats": "Total invited: {total}\nCurrent bonus: {bonus}\nTop-10:\n{leaders}",
        "referral_settings_panel": "Referral settings:\nBonus per friend: {bonus}\nWelcome bonus: {welcome_bonus}\nStatus: {status}",
    },
}


BUTTONS = {
    "ru": {
        "tarot": "🔮 Таро",
        "another": "Сделать ещё",
        "share": "Поделиться",
        "profile": "⭐ Мой профиль",
        "help": "ℹ️ Помощь",
        "back": "Вернуться в меню",
        "change_name": "Изменить имя",
        "change_birth": "Изменить дату",
        "change_lang": "Изменить язык",
        "delete": "Удалить данные",
        "destiny": "Число судьбы",
        "name": "Число имени",
        "personality": "Карта личности",
        "compat": "Совместимость",
        "tarot_one": "Совет дня (1 карта)",
        "tarot_three": "Три карты",
        "tarot_situation": "Ситуация",
        "tarot_love": "Любовь",
        "tarot_career": "Карьера/финансы",
        "rune": "🪄 Руна дня",
        "metaphor": "💭 Метафора дня",
        "admin_stats": "📊 Статистика",
        "admin_broadcast": "📢 Рассылка",
        "admin_back": "⬅️ В меню",
        "admin_referral_settings": "⚙️ Рефералы",
        "admin_referral_increase": "+1",
        "admin_referral_decrease": "–1",
        "admin_referral_toggle": "Вкл/Выкл",
        "referral_bonus_label": "Бонус за реферала",
        "invite": "🤝 Пригласить друга",
        "referrals": "👥 Мои рефералы",
    },
    "en": {
        "tarot": "🔮 Tarot",
        "another": "Do one more",
        "share": "Share",
        "profile": "⭐ My profile",
        "help": "ℹ️ Help",
        "back": "Back to menu",
        "change_name": "Edit name",
        "change_birth": "Edit birth date",
        "change_lang": "Change language",
        "delete": "Delete data",
        "destiny": "Life path number",
        "name": "Name number",
        "personality": "Personality card",
        "compat": "Compatibility",
        "tarot_one": "One-card advice",
        "tarot_three": "Three cards",
        "tarot_situation": "Situation",
        "tarot_love": "Love",
        "tarot_career": "Career/finance",
        "rune": "🪄 Rune of the day",
        "metaphor": "💭 Metaphor of the day",
        "admin_stats": "📊 Stats",
        "admin_broadcast": "📢 Broadcast",
        "admin_back": "⬅️ To menu",
        "admin_referral_settings": "⚙️ Referrals",
        "admin_referral_increase": "+1",
        "admin_referral_decrease": "–1",
        "admin_referral_toggle": "On/Off",
        "referral_bonus_label": "Referral bonus",
        "invite": "🤝 Invite a friend",
        "referrals": "👥 My referrals",
    },
}


def t(key: str, lang: str = "ru", **kwargs) -> str:
    template = MESSAGES.get(lang, MESSAGES["ru"]).get(key, key)
    return template.format(**kwargs)


def button_text(key: str, lang: str = "ru") -> str:
    return BUTTONS.get(lang, BUTTONS["ru"]).get(key, key)
